name: OCR Workflow

on: [push, pull_request]
jobs:
  ocr:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:mantic
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
      - name: Install and remove dependencies
        run: |
          apt-get update && apt-get install -y software-properties-common 
          add-apt-repository universe
          apt-get install -y tesseract-ocr
      - name: Print and list tesseract version and languages
        run: tesseract -v && tesseract --list-langs
        
