name: OCR Workflow

on: [push, pull_request]
jobs:
  ocr:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: actions/checkout@main
      - name: Install Dependencies
        run: |
          apt-get update &&  apt-get install -y --no-install-recommends wget pdftk poppler-utils tesseract-ocr
      - name: Tesseract Commands 
        run: tesseract -v && tesseract --list-langs
      - name: Run Code
        run: bash ocr.sh
      - name: Upload as artifact
        uses: actions/upload-artifact@main
        with:
          name: file.pdf
          path: output.pdf
          
