name: OCR Workflow

on: [push, pull_request]
jobs:
  ocr:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:mantic
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends tesseract-ocr which && \
          chmod a+x $(which pip) && $(which pip) install --upgrade pytesseract os requests pdf2image reportlab
      - name: Tesseract Commands 
        run: tesseract -v && tesseract --list-lang
      - name: Run Code
        run: $(which python3) ocr.py

        
