name: OCR Workflow

on: [push, pull_request]

jobs:
  ocr:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:mantic
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y software-properties-common 
          add-apt-repository universe
          apt-get install -y tesseract-ocr tesseract-dev
      - name: List supported languages
        run: tesseract --list-langs
        
